# Generated by Django 2.1.1 on 2018-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
                ('cnf_psw', models.CharField(max_length=100)),
            ],
        ),
    ]
