# Generated by Django 2.1.1 on 2018-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_form',
            name='cnf_psw',
        ),
        migrations.RemoveField(
            model_name='test_form',
            name='psw',
        ),
        migrations.AddField(
            model_name='test_form',
            name='add',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='cln',
            field=models.CharField(default='college', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='cnt',
            field=models.CharField(default='phone', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='cty',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='f_name',
            field=models.CharField(default='father', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='wrks',
            field=models.CharField(default='workshop', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_form',
            name='email',
            field=models.EmailField(default='email', max_length=100),
        ),
    ]
