# Generated by Django 2.1.1 on 2018-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0002_auto_20180929_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_form',
            old_name='cty',
            new_name='cty_w',
        ),
        migrations.AddField(
            model_name='test_form',
            name='cent',
            field=models.CharField(default='center', max_length=100),
        ),
        migrations.AddField(
            model_name='test_form',
            name='cty_l',
            field=models.CharField(default='current_city', max_length=100),
        ),
    ]
