# Generated by Django 2.1.1 on 2018-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0005_workshopform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('f_name', models.CharField(default='father', max_length=100)),
                ('email', models.EmailField(default='email', max_length=100)),
                ('contact', models.CharField(default='phone', max_length=100)),
                ('add', models.CharField(default='address', max_length=100)),
                ('college', models.CharField(default='college', max_length=100)),
                ('cty_w', models.CharField(default='city', max_length=100)),
                ('cty_l', models.CharField(default='current_city', max_length=100)),
                ('cent', models.CharField(default='center', max_length=100)),
            ],
        ),
    ]
