# Generated by Django 2.1.1 on 2018-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0006_hackathonform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('email', models.EmailField(default='email', max_length=100)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
