# Generated by Django 2.1.1 on 2018-10-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0009_auto_20181002_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkshopForm',
            new_name='InternshipForm',
        ),
    ]
