# Generated by Django 2.1.1 on 2018-10-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0011_auto_20181015_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_form',
            old_name='wrks',
            new_name='internship',
        ),
    ]
