# Generated by Django 2.1.1 on 2018-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0012_auto_20181015_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_form',
            name='cty_w',
            field=models.CharField(default='city_for_internship', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_form',
            name='internship',
            field=models.CharField(default='internship', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_form',
            name='parent_contact',
            field=models.CharField(default='parent_contact', max_length=100),
        ),
    ]
