# Generated by Django 2.1.1 on 2018-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0014_auto_20181015_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipform',
            old_name='cty_w',
            new_name='cty_i',
        ),
        migrations.RemoveField(
            model_name='hackathonform',
            name='cty_w',
        ),
        migrations.RemoveField(
            model_name='hackathonform',
            name='f_name',
        ),
        migrations.AddField(
            model_name='hackathonform',
            name='cty_h',
            field=models.CharField(default='city_for_hackathon', max_length=100),
        ),
        migrations.AddField(
            model_name='hackathonform',
            name='parent_contact',
            field=models.CharField(default='parent_contact', max_length=100),
        ),
    ]
