# Generated by Django 2.1.1 on 2018-10-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0015_auto_20181015_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonform',
            old_name='cty_h',
            new_name='hackathon',
        ),
        migrations.RemoveField(
            model_name='hackathonform',
            name='cent',
        ),
    ]
