# Generated by Django 2.1.1 on 2018-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0018_auto_20181025_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipform',
            name='review',
        ),
        migrations.AddField(
            model_name='hackathonform',
            name='review',
            field=models.CharField(default='review', max_length=100),
        ),
    ]
