# Generated by Django 2.1.1 on 2018-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0019_auto_20181025_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='review',
            field=models.CharField(default='review', max_length=100),
        ),
    ]
