# Generated by Django 2.1.1 on 2018-11-03 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0020_internshipform_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonform',
            name='review_message',
            field=models.CharField(default='review message', max_length=500),
        ),
        migrations.AddField(
            model_name='hackathonform',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='internshipform',
            name='review_message',
            field=models.CharField(default='review message', max_length=500),
        ),
        migrations.AddField(
            model_name='internshipform',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
