# Generated by Django 2.1.1 on 2018-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0022_datavirtualizationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavirtualizationform',
            name='cent',
            field=models.CharField(default='center', max_length=100),
        ),
    ]
