# Generated by Django 2.1.4 on 2019-01-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0023_datavirtualizationform_cent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_id', models.CharField(max_length=10)),
                ('picture', models.FileField(upload_to='media/students/')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=15)),
                ('program_name', models.CharField(max_length=15)),
                ('communication_skills', models.IntegerField(default=0)),
                ('ability_to_grasp', models.IntegerField(default=0)),
                ('technical_skills', models.IntegerField(default=0)),
                ('average_performance', models.IntegerField(default=0)),
                ('performance_expected', models.IntegerField(default=0)),
            ],
        ),
    ]
