# Generated by Django 2.1.4 on 2019-01-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0025_auto_20190102_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('company_criteria', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('contact_no', models.CharField(max_length=13)),
                ('paren_name', models.CharField(max_length=50)),
                ('parent_gaurdian_contact_no', models.CharField(max_length=13)),
                ('college_name', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=20)),
                ('internship_course', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=80)),
            ],
        ),
    ]
