# Generated by Django 2.1.4 on 2019-01-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0028_auto_20190120_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='course',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='codemania_app.CourseDesc'),
        ),
    ]
