# Generated by Django 2.1.4 on 2019-01-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0029_auto_20190120_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='skills_required',
        ),
        migrations.AlterField(
            model_name='companies',
            name='course',
            field=models.ForeignKey(default='course', on_delete=django.db.models.deletion.CASCADE, to='codemania_app.Course'),
        ),
    ]
