# Generated by Django 2.1.4 on 2019-01-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0030_auto_20190120_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='course',
            field=models.ForeignKey(default='course', on_delete=django.db.models.deletion.CASCADE, to='codemania_app.CourseDesc'),
        ),
    ]
