# Generated by Django 2.1.4 on 2019-01-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0031_auto_20190120_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(default='Hyderabad, Telangana.', max_length=50)),
                ('job_description', models.TextField(default='No Job Description')),
                ('technolgy', models.CharField(default='Technology', max_length=50)),
                ('salary', models.CharField(max_length=9)),
                ('resume', models.FileField(upload_to='media/winter_internship_resumes')),
                ('skills', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='codemania_app.Course')),
            ],
        ),
    ]
