# Generated by Django 2.1.4 on 2019-01-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0034_auto_20190122_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='skills',
        ),
    ]
