# Generated by Django 2.1.4 on 2019-01-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0035_remove_companydetail_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='course',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
