# Generated by Django 2.1.7 on 2019-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0036_auto_20190122_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('email', models.CharField(default='email', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
        migrations.DeleteModel(
            name='CompanyForm',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.DeleteModel(
            name='HackathonForm',
        ),
        migrations.DeleteModel(
            name='InternshipForm',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDesc',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
