# Generated by Django 2.1.7 on 2019-03-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0040_auto_20190303_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_table',
            name='spec',
        ),
    ]
