# Generated by Django 2.1.7 on 2019-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemania_app', '0041_remove_patient_table_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_table',
            name='uid',
            field=models.CharField(default='uid', max_length=13),
        ),
    ]
